### ISSUE TITLE
Any chance you can add support for .aseprite format?

### ISSUE THREAD

**Issue by HappyCappybara** [Uncle-Uee/sprite-extractor-tool#1]
This is a great asset, but unfortunately the majority of my spritesheets are .aseprite format.

I attempted to modify your code to use the AsepriteImporter from the Aseprite Unity package, and that works, but when calling newTexture.EncodeTexture2D(format), there is no case for .aseprite.

I looked up the encoding but I'm not sure how to proceed with implementing it.
https://github.com/aseprite/aseprite/blob/main/docs/ase-file-specs.md

Cheers

**Comment by Uncle-Uee** [comment]
Yo. Sorry I hardly check issues on this asset. 
I can definitely give this a peep and see what I can do. I'm not familiar with aseprite format but that link in your post gives a good general idea of what to do.

No promises though.

**Comment by Uncle-Uee** [comment]
@HappyCappybara 
Hey man, so I used the Unity Aseprite package to get this working. 
It does the job of just extracting the individual sprites of an aseprite asset. 

Hope this helps. 
[AsepriteSpriteExtractor.zip](https://github.com/user-attachments/files/15945387/AsepriteSpriteExtractor.zip)
